name: First workflow

on: push

jobs: 
  build: 
    run-osi: ubuntu-latest

    
    steps: 
    - uses: actions/checkout@v3
    - name: Run a sample github action
    - run: echo "workflow run for action"
