name: Linting-python-code

on:
  push:
    branches:
      - main

jobs:
  python-linting-code:
    runs-on: ubuntu-latest
    steps:
      - name: Super-linter
        uses: super-linter/super-linter@v6.8.0
